algoritmo "semnome"

var
n,n1:inteiro
soma,divi:real
resp:caractere
inicio
Escreva("Indique um número: ")
leia(n)
Escreva("indique outro numero: ")
leia(n1)
soma <- N + n1
divi <- n/n1
Escreva("Deseja ver a soma (s) ou a divisão (d)? ")
leia (resp)
se (resp = "s") entao
   Escreval("A soma é: ",soma)
fimse
se (resp = "d") entao
   escreval("A divisão é: ",divi:4:6)
fimse
fimalgoritmo
